"""Shared helper for scan_clr80.py / scan_byte7.py: the whole-code-section ppcdis listing.

`lines(path)` returns the listing split into lines: read from `path` when given (a file made by
`python3 docs/cythera/tools/ppcdis.py 10000000 100cd280 > all.dis`), else generated by running
ppcdis.py on that range in a subprocess (about 210k lines). Stdlib only.
⚑ corrected (review wave 3 2026-10-06): run as a script it takes the same optional `all.dis`, prints
the line count `lines()` returns, and exits 0 on `--help`; a missing file is a one-line error.
"""
import argparse, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def lines(path=None):
    if path:
        return open(path).read().split('\n')
    out = subprocess.run([sys.executable, os.path.join(HERE, 'ppcdis.py'), '10000000', '100cd280'],
                         check=True, capture_output=True, text=True).stdout
    return out.split('\n')


def cli(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('listing', nargs='?', metavar='all.dis',
                    help='whole-code ppcdis listing (default: generate it in-process)')
    a = ap.parse_args(argv)
    if a.listing is not None and not os.path.isfile(a.listing):
        sys.exit('%s: error: no such file: %s' % (ap.prog, a.listing))
    print(len(lines(a.listing)))


if __name__ == '__main__':
    cli()
