"""Shared helper for scan_clr80.py / scan_byte7.py: the whole-code-section ppcdis listing.

`lines(path)` returns the listing split into lines: read from `path` when given (a file made by
`python3 docs/cythera/tools/ppcdis.py 10000000 100cd280 > all.dis`), else generated by running
ppcdis.py on that range in a subprocess (about 210k lines). Stdlib only.
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def lines(path=None):
    if path:
        return open(path).read().split('\n')
    out = subprocess.run([sys.executable, os.path.join(HERE, 'ppcdis.py'), '10000000', '100cd280'],
                         check=True, capture_output=True, text=True).stdout
    return out.split('\n')
