# tools/windows/env.sh — shared paths and pins for the Windows cross-compile (plan W0).
# Source it:  . tools/windows/env.sh
# Everything big lives in $WIN_CROSS (outside git); setup-toolchain.sh fills it.

# ---- Pins (change together; see README.md) ---------------------------------------------------
SWIFT_WIN_VERSION="6.4.0"                     # swift.org release: macOS toolchain + Windows SDK must match
SWIFT_WIN_TAG="swift-${SWIFT_WIN_VERSION}-RELEASE"
MSVC_VERSION="14.44.17.14"                    # MSVC CRT, via xwin (Microsoft licence accepted by Ben, D15)
WINSDK_VERSION="10.0.26100"                   # Windows SDK, via xwin; UCRT headers from the same SDK
SDL3_VERSION="3.4.16"                        # SDL3 official Windows VC dev zip (libsdl-org); = brew sdl3 on the Mac

# ---- Locations ---------------------------------------------------------------------------------
WIN_CROSS="${WIN_CROSS:-$HOME/Developer/Toolchains/windows-cross}"
WIN_DOWNLOADS="$WIN_CROSS/downloads"
WIN_TOOLCHAIN="$WIN_CROSS/${SWIFT_WIN_TAG}.xctoolchain"          # open-source macOS toolchain (extracted pkg)
WIN_PLATFORM="$WIN_CROSS/Windows.platform"                         # from the Windows installer's windows.msi
WIN_SDK="$WIN_PLATFORM/Developer/SDKs/Windows.sdk"
WIN_XCTEST="$WIN_PLATFORM/Developer/Library/XCTest-${SWIFT_WIN_VERSION}"
WIN_TESTING="$WIN_PLATFORM/Developer/Library/Testing-${SWIFT_WIN_VERSION}"
WIN_RUNTIME="$WIN_CROSS/runtime-x64"                                # Swift runtime DLLs (rtl.amd64.msi) + VC redist
WIN_SYSROOT="$WIN_CROSS/winsysroot"                                 # xwin splat --use-winsysroot-style
WIN_VCTOOLS="$WIN_SYSROOT/VC/Tools/MSVC/$MSVC_VERSION"
WIN_KITS="$WIN_SYSROOT/Windows Kits/10"
WIN_SDL3="$WIN_CROSS/SDL3-$SDL3_VERSION"
WIN_SWIFT_SDKS="$WIN_CROSS/swift-sdks"                              # --swift-sdks-path (generated by setup)
WIN_SDK_BUNDLE="windows-x86_64.artifactbundle"

CX_BIN="/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin"
HECTOR_BOTTLE="${HECTOR_BOTTLE:-hector-win}"
HECTOR_BOTTLE_DIR="$HOME/Library/Application Support/CrossOver/Bottles/$HECTOR_BOTTLE"

WIN_TRIPLE="x86_64-unknown-windows-msvc"

# Mac path -> Windows path through the bottle's Z: drive (Z: -> /).
win_path() {
    local abs
    abs="$(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")"
    printf 'Z:%s' "$abs" | tr '/' '\\'
}
