#!/usr/bin/env python3
"""Generate Aki/Core/Sources/AkiCore/LayoutTables.swift from docs/aki/levels-layouts.md (plan P2.1).

The bank's tables are the literal `_AddTile(double x, double y, short L)` arguments of each `_LayoutN`
in call order; x and y are multiples of 0.5. Each level becomes one flat [Int] of (x2, y2, L) triples
(x2 = 2x, y2 = 2y — `_AddTile`'s stored half-units), 8 triples per line, plus the section header's
function name, g+0x94 / g+0x98 draw offsets and g+0x8e background. Deterministic: rerunning on an
unchanged bank rewrites the same bytes. Exits 1 unless there are 12 levels (1..12) of 144 tuples each.
Usage: python3 tools/gen-aki-layouts.py   (from anywhere; paths resolve from this file)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = "docs/aki/levels-layouts.md"
TARGET = "Aki/Core/Sources/AkiCore/LayoutTables.swift"

SECTION = re.compile(r"^### Level (\d+) — `(_Layout\d+)`")
HEADER = re.compile(r"^draw offset g\+0x94 = (-?\d+), g\+0x98 = (-?\d+); background index g\+0x8e = (-?\d+);")
TUPLE = re.compile(r"\((-?[0-9.]+),(-?[0-9.]+),([0-9])\)")


def half_units(text, where):
    doubled = float(text) * 2
    if doubled != int(doubled):
        sys.exit(f"error: {where}: {text} is not a multiple of 0.5")
    return int(doubled)


def parse(path):
    levels = []
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip("\n")
            m = SECTION.match(line)
            if m:
                levels.append({"level": int(m.group(1)), "name": m.group(2), "header": None, "tuples": []})
                continue
            if line.startswith("#"):
                if levels and not line.startswith("### Level"):
                    levels[-1]["closed"] = True
                continue
            if not levels or levels[-1].get("closed"):
                continue
            m = HEADER.match(line)
            if m:
                levels[-1]["header"] = tuple(int(g) for g in m.groups())
                continue
            if line.startswith("|"):
                for x, y, layer in TUPLE.findall(line):
                    where = f"{path}:{n}"
                    levels[-1]["tuples"].append((half_units(x, where), half_units(y, where), int(layer)))
    return levels


def render(levels):
    out = [
        "// GENERATED by tools/gen-aki-layouts.py from docs/aki/levels-layouts.md — do not edit.",
        "// Per level: `_LoadLayout`'s function, its g+0x94 / g+0x98 draw offsets and g+0x8e background, and the",
        "// `_AddTile(x, y, L)` calls in call order as flat (x2 = 2x, y2 = 2y, L) triples, 8 triples per line.",
        "",
        "extension Layouts {",
        "    static let tables: [LayoutTable] = [",
    ]
    for lv in levels:
        dx, dy, bg = lv["header"]
        out.append(f"        LayoutTable(level: {lv['level']}, functionName: \"{lv['name']}\", "
                   f"offsetX: {dx}, offsetY: {dy}, background: {bg}, triples: level{lv['level']:02d}),")
    out.append("    ]")
    for lv in levels:
        out.append("")
        out.append(f"    /// Level {lv['level']} — `{lv['name']}`: {len(lv['tuples'])} placements.")
        out.append(f"    private static let level{lv['level']:02d}: [Int] = [")
        t = lv["tuples"]
        for i in range(0, len(t), 8):
            out.append("        " + ",  ".join(f"{x2}, {y2}, {layer}" for x2, y2, layer in t[i:i + 8]) + ",")
        out.append("    ]")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    levels = parse(os.path.join(ROOT, SOURCE))
    bad = [f"level {lv['level']} ({lv['name']}): {len(lv['tuples'])} tuples" for lv in levels if len(lv["tuples"]) != 144]
    bad += [f"level {lv['level']} ({lv['name']}): no draw-offset header" for lv in levels if lv["header"] is None]
    if [lv["level"] for lv in levels] != list(range(1, 13)):
        bad.append(f"levels found {[lv['level'] for lv in levels]}, expected 1..12 in order")
    if bad:
        print("error: " + "; ".join(bad), file=sys.stderr)
        sys.exit(1)
    with open(os.path.join(ROOT, TARGET), "w", encoding="utf-8", newline="\n") as f:
        f.write(render(levels))
    print(f"wrote {TARGET}: {len(levels)} layouts, {sum(len(lv['tuples']) for lv in levels)} placements")


if __name__ == "__main__":
    main()
